spring:
    profiles: dev
    datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/test
       username: root
       password: password
    jpa:
       show-sql: true
       hibernate.ddl-auto: update
       hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy   
       properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    maxActive: 100
    maxIdle: 100
    minIdle: 10
    initialSize: 0
server:
    port: 9000
